name: Build CV

on:
  push:
    paths:
      - "src/**"
      - "assets/**"
      - "Makefile"
      - ".github/workflows/build.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug repository structure
        run: |
          pwd
          ls -R

      - name: Test logo file
        run: |
          ls assets/logo-crop.pdf

      - name: Install LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: src/cv.tex
          compile: false

      - name: Build
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: output/*.pdf
